USE ROLE ACCOUNTADMIN;

-- Roles
SET MY_USER = CURRENT_USER();
CREATE OR REPLACE ROLE TEAM2_ROLE;
GRANT ROLE TEAM2_ROLE TO ROLE SYSADMIN;
GRANT ROLE TEAM2_ROLE TO USER IDENTIFIER($MY_USER);

GRANT EXECUTE TASK ON ACCOUNT TO ROLE TEAM2_ROLE;
GRANT MONITOR EXECUTION ON ACCOUNT TO ROLE TEAM2_ROLE;
GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE TO ROLE TEAM2_ROLE;

-- Databases
CREATE OR REPLACE DATABASE TEAM2_DB;
GRANT OWNERSHIP ON DATABASE TEAM2_DB TO ROLE TEAM2_ROLE;

-- Warehouses
CREATE OR REPLACE WAREHOUSE TEAM2_DW WAREHOUSE_SIZE = XSMALL, AUTO_SUSPEND = 300, AUTO_RESUME= TRUE;
GRANT OWNERSHIP ON WAREHOUSE TEAM2_DW TO ROLE TEAM2_ROLE;


-- ----------------------------------------------------------------------------
-- Step #3: Create the database level objects
-- ----------------------------------------------------------------------------
USE ROLE TEAM2_ROLE;
USE WAREHOUSE TEAM2_DW;
USE DATABASE TEAM2_DB;

-- Schemas
CREATE OR REPLACE SCHEMA NFL_SPONSOR;
CREATE OR REPLACE SCHEMA APP_USES;
CREATE OR REPLACE SCHEMA CONSUMER_INFO;
CREATE OR REPLACE SCHEMA ANALYTICS;
