USE ROLE TEAM2_ROLE;
USE WAREHOUSE TEAM2_DW;
USE DATABASE TEAM2_DB;
USE SCHEMA ANALYTICS;

CREATE OR REPLACE TABLE SPONSOR_EXPOSURE AS
SELECT
    VSE.POST_DATE,
    VSE.PLATFORM_NAME,
    VSE.RIGHTSHOLDER_NAME AS TEAM_NAME,
    VSE.SPONSOR_NAME AS SPONSOR,
    VSE.PLACEMENT_TYPE_NAME AS PLACEMENT_TYPE,
    VSE.ACCOUNT_OWNERSHIP_NAME AS ACCOUNT_OWNERSHIP,
    VSE.SUM_IMPRESSIONS,
    VSE.ENGAGEMENTS,
    VSE.SUM_FMV AS FULL_MEDIAL_VALUE,
    TSL.STATE_CODE
    FROM
    NFL_SPONSOR.SPORTS.VW_SAMPLE_SPONSOR_EXPOSURES_BY_DAY VSE
JOIN
    TEAM2_DB.NFL_SPONSOR.TEAM_STATE_LOOKUP TSL
ON
    VSE.RIGHTSHOLDER_NAME = TSL.TEAM_NAME;


CREATE OR REPLACE STREAM TEAM2_DB.ANALYTICS.SPONSOR_EXPOSURE_STREAM
  ON TABLE SPONSOR_EXPOSURE
  SHOW_INITIAL_ROWS = TRUE;

SELECT * from TEAM2_DB.ANALYTICS.SPONSOR_EXPOSURE limit 10;
