USE ROLE TEAM2_ROLE;
USE WAREHOUSE TEAM2_DW;
USE DATABASE TEAM2_DB;
USE SCHEMA ANALYTICS;

CREATE OR REPLACE TABLE CONSUMER_DATA AS
(SELECT
    FIRST_NAME,
    MI,
    LAST_NAME,
    ADDRESS,
    SUITE_APT,
    CITY,
    STATE,
    ZIP5,
    TELEPHONE_NUMBER,
    TIME_ZONE,
    GENDER_CODE,
    DATE_OF_BIRTH_YEAR,
    DATE_OF_BIRTH_MONTH,
    DATE_OF_BIRTH_DAY,
    EXACT_AGE_BASED_OFF_DOB,
    INCOME_ESTIMATED_HOUSEHOLD,
    NET_WORTH,
    OCCUPATION,
    OCCUPATION_DETAIL,
    EMAIL_ADDRESS,
    PERM_INDIVIDUAL_ID
FROM
   CONSUMER_INFO.PUBLIC.CONSUMER_TEST_DATA_VIEW);

ALTER TABLE CONSUMER_DATA
ADD ACTIVE_ENTHUSIATS NVARCHAR(4000);

UPDATE TEAM2_DB.ANALYTICS.CONSUMER_DATA CD
SET ACTIVE_ENTHUSIATS = TEAM2_DB.CONSUMER_INFO.GET_ACTIVE_BEHAVIORS(OBJECT_CONSTRUCT(CTDV.*)) 
from  CONSUMER_INFO.PUBLIC.CONSUMER_TEST_DATA_VIEW CTDV where CTDV.perm_individual_id = CD.PERM_INDIVIDUAL_ID;

CREATE OR REPLACE STREAM TEAM2_DB.ANALYTICS.CONSUMER_DATA_STREAM
  ON TABLE CONSUMER_DATA
  SHOW_INITIAL_ROWS = TRUE;

select * from  TEAM2_DB.ANALYTICS.CONSUMER_DATA;
