USE ROLE TEAM2_ROLE;
USE WAREHOUSE TEAM2_DW;
USE DATABASE TEAM2_DB;
USE SCHEMA ANALYTICS;

CREATE OR REPLACE TABLE PANELIST_APP_USAGE AS
SELECT
    AV.APP_CATEGORY,
    AV.APP_NAME,
    AV.DURATION_SEC,
    PD.BIRTHDAY,
    PD.AGE,
    PD.AGE_RANGE,
    PD.GENDER,
    PD.ETHNICITY,
    PD.INCOME,
    PD.EDUCATION,
    PD.EMPLOYMENT_STATUS,
    PD.MARITAL_STATUS,
    PD.STATE,
    PD.POSTAL_CODE,
    PD.REGION,
    PD.DMA,
    APP_USES.GET_GENERATION_CLASSIFICATION(YEAR(TO_DATE(PD.BIRTHDAY)))::STRING as GENERATION
FROM
    APP_USES.MFOUR_SHARE.APP_VISIT AV
JOIN
    APP_USES.MFOUR_SHARE.PANELIST_DEMOGRAPHIC PD
ON
    AV.PANELIST_ID = PD.PANELIST_ID;

CREATE OR REPLACE STREAM TEAM2_DB.ANALYTICS.PANELIST_APP_USAGE_STREAM
  ON TABLE PANELIST_APP_USAGE
  SHOW_INITIAL_ROWS = TRUE;

SELECT * from TEAM2_DB.ANALYTICS.PANELIST_APP_USAGE limit 10;