
USE ROLE ACCOUNTADMIN;

DROP DATABASE TEAM2_DB;
DROP WAREHOUSE TEAM2_DW;
DROP ROLE TEAM2_ROLE;

-- Drop the weather share
DROP DATABASE NFl_SPONSOR;
DROP DATABASE CONSUMER_INFO;
DROP DATABASE APP_USES;